apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-tolerations-scalesetpriority
  annotations:
    policies.kyverno.io/title: Add Tolerations
    policies.kyverno.io/category: Other
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.7.1
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.25"
    policies.kyverno.io/description: >- 
      Pod tolerations are used to schedule on Nodes which have
      a matching taint. This policy adds the toleration `kubernetes.azure.com/scalesetpriority=spot:NoSchedule`
      if existing tolerations do not contain the key `kubernetes.azure.com/scalesetpriority`.
spec:
  rules:
  - name: service-toleration
    match:
      any:
      - resources:
          names:
          - "sas-workload-orchestrator-scaling-pod-*"
          kinds:
          - Pod
    preconditions:
      any:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: AnyNotIn
        value: "{{ request.object.spec.tolerations[].key || `[]` }}"
    mutate:
      patchesJson6902: |-
        - op: add
          path: "/spec/tolerations/-"
          value:
            key: kubernetes.azure.com/scalesetpriority
            operator: Equal
            value: spot
            effect: NoSchedule        

